/* The following code was generated by JFlex 1.7.0 tweaked for IntelliJ platform */

package com.avokin.ideaLogViewer.lang.lexer;


import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;
import java.util.Stack;

import com.intellij.psi.TokenType;

import static com.avokin.ideaLogViewer.lang.psi.IdeaLogViewerTokenTypes.*;

/**
 * The IdeaLogViewer lexer
 *
 * @author Andrey Vokin
 */

public class _IdeaLogLexer implements FlexLexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;
  private static final String ZZ_NL = System.getProperty("line.separator");

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int YY_CLASS_NAME = 2;
  public static final int YY_AFTER_CLASS_NAME = 4;
  public static final int YY_LOG_RECORD = 6;
  public static final int YY_UPTIME = 8;
  public static final int YY_TEXT_UNTIL_END_OF_LINE = 10;
  public static final int YY_STACK_TRACE_LINE = 12;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6, 6
  };

  /**
   * Translates characters to character classes
   * Chosen bits are [10, 6, 5]
   * Total runtime size is 4224 bytes
   */
  public static int ZZ_CMAP(int ch) {
    return ZZ_CMAP_A[(ZZ_CMAP_Y[(ZZ_CMAP_Z[ch>>11]<<6)|((ch>>5)&0x3f)]<<5)|(ch&0x1f)];
  }

  /* The ZZ_CMAP_Z table has 544 entries */
  static final char ZZ_CMAP_Z[] = zzUnpackCMap(
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\15\5\1\7\1\10\11\5\1\11\1\12\1\5\1\13\1\14\11"+
    "\5\1\15\14\5\1\16\2\5\1\17\u01e2\5");

  /* The ZZ_CMAP_Y table has 1024 entries */
  static final char ZZ_CMAP_Y[] = zzUnpackCMap(
    "\1\0\1\1\1\2\1\3\1\4\1\5\55\4\1\6\3\4\1\7\6\4\1\6\14\4\1\10\3\4\1\10\3\4\1"+
    "\10\3\4\1\10\3\4\1\10\3\4\1\10\3\4\1\10\3\4\1\10\3\4\1\10\3\4\1\10\2\4\1\7"+
    "\3\4\1\7\2\4\1\6\10\4\1\6\1\4\1\7\57\4\1\5\12\4\1\6\1\11\11\4\1\10\3\4\1\7"+
    "\5\4\1\12\5\4\1\7\2\4\1\7\4\4\1\12\35\4\1\13\1\14\1\15\175\4\1\5\160\4\1\6"+
    "\24\4\1\7\1\4\1\6\5\4\2\7\2\4\1\7\14\4\1\7\130\4\1\7\54\4\1\6\35\4\1\10\3"+
    "\4\1\7\1\4\1\16\4\4\1\7\10\4\1\7\12\4\1\7\3\4\1\7\13\4\1\7\3\4\1\6\2\4\1\7"+
    "\15\4\1\6\32\4\1\7\60\4\1\6\6\4\1\7\143\4\1\17\1\20\12\4\1\7\65\4");

  /* The ZZ_CMAP_A table has 544 entries */
  static final char ZZ_CMAP_A[] = zzUnpackCMap(
    "\11\0\1\10\1\1\3\2\22\0\1\5\7\0\1\15\1\16\2\0\1\7\1\4\1\13\1\0\12\14\1\6\6"+
    "\0\1\33\1\23\1\13\1\21\1\22\1\30\1\25\1\13\1\26\4\13\1\27\1\31\2\13\1\34\2"+
    "\13\1\24\1\13\1\32\3\13\1\17\1\0\1\20\1\0\1\13\1\0\1\11\22\13\1\12\6\13\45"+
    "\0\1\2\37\0\12\3\46\0\12\3\14\0\12\3\36\0\1\2\1\0\12\3\6\0\12\3\6\0\12\3\6"+
    "\0\14\2\34\0\2\2\5\0\1\2\57\0\1\2\26\0\12\3\16\0\62\3");

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\7\0\1\1\1\2\1\1\1\3\1\1\1\4\1\5"+
    "\2\2\4\1\1\6\1\2\1\7\1\10\1\11\1\12"+
    "\1\11\2\1\7\0\1\11\4\0\1\13\1\14\4\0"+
    "\1\11\5\0\1\15\1\16\2\11\2\0\1\17\1\20"+
    "\1\11\2\0\1\11\1\21\2\0\1\11\1\0\1\11"+
    "\2\0\1\11\1\0\1\11\2\0\1\22\10\0\1\23";

  private static int [] zzUnpackAction() {
    int [] result = new int[88];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\35\0\72\0\127\0\164\0\221\0\256\0\313"+
    "\0\313\0\350\0\u0105\0\u0122\0\u013f\0\313\0\u015c\0\u0179"+
    "\0\u0196\0\u01b3\0\u01d0\0\u01ed\0\u020a\0\u0227\0\313\0\313"+
    "\0\u0244\0\313\0\u0261\0\u027e\0\u029b\0\u02b8\0\u02d5\0\u02f2"+
    "\0\u030f\0\u032c\0\u0349\0\u0366\0\u0383\0\u03a0\0\u029b\0\u03bd"+
    "\0\u03da\0\313\0\u02f2\0\u03f7\0\u0414\0\u0431\0\u044e\0\u046b"+
    "\0\u0488\0\u04a5\0\u04c2\0\u04df\0\u04fc\0\313\0\313\0\u0519"+
    "\0\313\0\u0536\0\u0553\0\313\0\313\0\u0570\0\u058d\0\u05aa"+
    "\0\u05c7\0\313\0\u05e4\0\u0601\0\u061e\0\u063b\0\u0658\0\u0675"+
    "\0\u0692\0\u06af\0\u06cc\0\u06e9\0\u0706\0\u0723\0\313\0\u0740"+
    "\0\u075d\0\u077a\0\u0797\0\u07b4\0\u07d1\0\u07ee\0\u080b\0\313";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[88];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\10\1\11\1\10\1\12\10\10\1\12\20\10\1\13"+
    "\1\10\2\13\1\10\1\14\2\13\1\10\24\13\1\15"+
    "\1\16\33\15\1\10\2\17\2\10\1\20\2\10\1\17"+
    "\10\10\1\21\1\22\3\10\1\23\3\10\1\24\3\10"+
    "\2\17\1\25\1\10\1\26\2\10\1\26\3\10\1\25"+
    "\2\10\1\27\1\30\14\10\1\31\1\32\3\31\1\33"+
    "\2\31\1\33\24\31\5\10\1\34\2\10\1\34\4\35"+
    "\4\10\14\35\40\0\1\36\10\0\1\36\20\0\1\13"+
    "\1\0\2\13\2\0\2\13\1\0\24\13\4\0\1\37"+
    "\30\0\1\15\1\0\33\15\1\0\2\17\2\0\1\17"+
    "\2\0\1\17\25\0\2\17\1\0\1\40\1\17\2\0"+
    "\1\17\46\0\1\41\46\0\1\42\27\0\1\43\40\0"+
    "\1\44\4\0\1\25\10\0\1\25\21\0\2\17\1\25"+
    "\1\0\1\26\2\0\1\26\3\0\1\25\20\0\1\31"+
    "\1\0\34\31\1\0\7\31\1\45\23\31\11\0\1\46"+
    "\34\0\4\47\1\50\3\0\14\47\3\0\1\51\10\0"+
    "\1\51\25\0\1\52\34\0\1\53\52\0\1\54\45\0"+
    "\1\55\30\0\1\56\40\0\1\57\1\31\1\0\10\31"+
    "\1\60\22\31\12\0\1\61\33\0\4\62\4\0\14\62"+
    "\3\0\1\63\10\0\1\63\44\0\1\64\41\0\1\65"+
    "\34\0\1\66\32\0\1\67\5\0\1\31\1\0\3\31"+
    "\1\70\2\31\1\70\24\31\5\0\1\71\2\0\1\71"+
    "\32\0\1\72\2\0\4\62\4\0\14\62\4\0\1\73"+
    "\55\0\1\74\43\0\1\75\1\31\1\0\7\31\4\76"+
    "\4\31\14\76\3\0\1\77\10\0\1\77\23\0\1\100"+
    "\10\0\1\100\20\0\1\31\1\0\7\31\4\76\1\101"+
    "\3\31\14\76\3\0\1\77\10\0\1\77\1\0\1\102"+
    "\21\0\1\103\1\104\7\0\1\103\20\0\1\31\1\0"+
    "\7\31\4\105\4\31\14\105\4\0\1\104\33\0\1\106"+
    "\10\0\1\106\20\0\1\31\1\0\4\31\1\107\2\31"+
    "\4\105\4\31\14\105\3\0\1\110\1\0\1\111\6\0"+
    "\1\110\20\0\1\31\1\0\1\31\1\112\10\31\1\112"+
    "\20\31\5\0\1\111\32\0\1\113\10\0\1\113\20\0"+
    "\1\31\1\0\1\31\1\112\10\31\1\112\1\31\1\114"+
    "\16\31\3\0\1\115\2\0\1\116\5\0\1\115\20\0"+
    "\1\31\1\117\33\31\6\0\1\116\31\0\1\120\10\0"+
    "\1\120\23\0\1\121\2\0\1\122\5\0\1\121\26\0"+
    "\1\122\31\0\1\123\10\0\1\123\23\0\1\124\3\0"+
    "\1\125\4\0\1\124\27\0\1\125\30\0\1\126\10\0"+
    "\1\126\23\0\1\127\10\0\1\127\23\0\1\130\10\0"+
    "\1\130\20\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2088];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String[] ZZ_ERROR_MSG = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\7\0\2\11\4\1\1\11\10\1\2\11\1\1\1\11"+
    "\3\1\7\0\1\1\4\0\1\11\1\1\4\0\1\1"+
    "\5\0\2\11\1\1\1\11\2\0\2\11\1\1\2\0"+
    "\1\1\1\11\2\0\1\1\1\0\1\1\2\0\1\1"+
    "\1\0\1\1\2\0\1\11\10\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[88];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
  private final Stack<Integer> stack = new Stack<Integer>();

  /**
   * Push the actual state on top of the stack
   */
  private void pushState() {
    stack.push(yystate());
  }

  /**
   * Push the actual state on top of the stack
   * and change into another state
   *
   * @param state The new state
   */
  private void pushStateAndBegin(int state) {
    stack.push(yystate());
    yybegin(state);
  }

  /**
   * Pop the last state from the stack and change to it.
   * If the stack is empty, go to YYINITIAL
   */
  private void popState() {
    if (!stack.empty()) {
      yybegin(stack.pop());
    } else {
      pushStateAndBegin(YYINITIAL);
    }
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public _IdeaLogLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /**
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    int size = 0;
    for (int i = 0, length = packed.length(); i < length; i += 2) {
      size += packed.charAt(i);
    }
    char[] map = new char[size];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < packed.length()) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  private static String zzToPrintable(CharSequence str) {
    StringBuilder builder = new StringBuilder();
    for (int n = 0 ; n < str.length() ; ) {
      int ch = Character.codePointAt(str, n);
      int charCount = Character.charCount(ch);
      n += charCount;
      if (ch > 31 && ch < 127) {
        builder.append((char)ch);
      } else if (charCount == 1) {
        builder.append(String.format("\\u%04X", ch));
      } else {
        builder.append(String.format("\\U%06X", ch));
      }
    }
    return builder.toString();
  }

  public final int getTokenStart() {
    return zzStartRead;
  }

  public final int getTokenEnd() {
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end, int initialState) {
    zzBuffer = buffer;
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL/*, zzEndReadL*/);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL/*, zzEndReadL*/);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + ZZ_CMAP(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            System.out.println("match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [134] { stack.clear();"+ZZ_NL+"                                pushStateAndBegin(YY_TEXT_UNTIL_END_OF_LINE);"+ZZ_NL+"                                yypushback(yylength()); }");
            { stack.clear();
                                pushStateAndBegin(YY_TEXT_UNTIL_END_OF_LINE);
                                yypushback(yylength());
            }
            // fall through
          case 20: break;
          case 2:
            System.out.println("match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [78] { return TokenType.WHITE_SPACE; }");
            { return TokenType.WHITE_SPACE;
            }
            // fall through
          case 21: break;
          case 3:
            System.out.println("match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [102] { return CLASS_NAME; }");
            { return CLASS_NAME;
            }
            // fall through
          case 22: break;
          case 4:
            System.out.println("match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [109] { return MESSAGE; }");
            { return MESSAGE;
            }
            // fall through
          case 23: break;
          case 5:
            System.out.println("match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [111] { stack.clear();"+ZZ_NL+"                                pushStateAndBegin(YYINITIAL);"+ZZ_NL+"                                return TokenType.WHITE_SPACE; }");
            { stack.clear();
                                pushStateAndBegin(YYINITIAL);
                                return TokenType.WHITE_SPACE;
            }
            // fall through
          case 24: break;
          case 6:
            System.out.println("match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [84] { return UPTIME; }");
            { return UPTIME;
            }
            // fall through
          case 25: break;
          case 7:
            System.out.println("match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [83] { return BRACKET_START; }");
            { return BRACKET_START;
            }
            // fall through
          case 26: break;
          case 8:
            System.out.println("match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [85] { pushStateAndBegin(YY_LOG_RECORD);"+ZZ_NL+"                                return BRACKET_END; }");
            { pushStateAndBegin(YY_LOG_RECORD);
                                return BRACKET_END;
            }
            // fall through
          case 27: break;
          case 9:
            System.out.println("match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [126] { return TEXT; }");
            { return TEXT;
            }
            // fall through
          case 28: break;
          case 10:
            System.out.println("match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [129] { popState();"+ZZ_NL+"                                return TEXT; }");
            { popState();
                                return TEXT;
            }
            // fall through
          case 29: break;
          case 11:
            System.out.println("match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [104] { pushStateAndBegin(YY_AFTER_CLASS_NAME);"+ZZ_NL+"                                return TEXT; }");
            { pushStateAndBegin(YY_AFTER_CLASS_NAME);
                                return TEXT;
            }
            // fall through
          case 30: break;
          case 12:
            System.out.println("match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [97] { pushStateAndBegin(YY_CLASS_NAME);"+ZZ_NL+"                               return TEXT; }");
            { pushStateAndBegin(YY_CLASS_NAME);
                               return TEXT;
            }
            // fall through
          case 31: break;
          case 13:
            System.out.println("match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [93] { return LOG_LEVEL_INFO; }");
            { return LOG_LEVEL_INFO;
            }
            // fall through
          case 32: break;
          case 14:
            System.out.println("match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [94] { return LOG_LEVEL_WARN; }");
            { return LOG_LEVEL_WARN;
            }
            // fall through
          case 33: break;
          case 15:
            System.out.println("match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [92] { return LOG_LEVEL_DEBUG; }");
            { return LOG_LEVEL_DEBUG;
            }
            // fall through
          case 34: break;
          case 16:
            System.out.println("match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [95] { return LOG_LEVEL_ERROR; }");
            { return LOG_LEVEL_ERROR;
            }
            // fall through
          case 35: break;
          case 17:
            System.out.println("match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [118] { popState();"+ZZ_NL+"                                return CODE_REFERENCE; }");
            { popState();
                                return CODE_REFERENCE;
            }
            // fall through
          case 36: break;
          case 18:
            System.out.println("match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [123] { pushStateAndBegin(YY_STACK_TRACE_LINE);"+ZZ_NL+"                                yypushback(yylength()); }");
            { pushStateAndBegin(YY_STACK_TRACE_LINE);
                                yypushback(yylength());
            }
            // fall through
          case 37: break;
          case 19:
            System.out.println("match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [75] { pushStateAndBegin(YY_UPTIME);"+ZZ_NL+"                                return TIME_STAMP; }");
            { pushStateAndBegin(YY_UPTIME);
                                return TIME_STAMP;
            }
            // fall through
          case 38: break;
          default:
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This main method is the debugging routine for the scanner.
   * It prints debugging information about each returned token to
   * System.out until the end of file is reached, or an error occured.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java _IdeaLogLexer [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          java.nio.charset.Charset.forName(encodingName); // Side-effect: is encodingName valid?
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        _IdeaLogLexer scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new _IdeaLogLexer(reader);
          do {
            System.out.println(scanner.advance());
          } while (!scanner.zzAtEOF);

        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
